version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis-net

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    networks:
      - redis-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  redis-net:
    driver: bridge

volumes:
  redis_data:
    driver: local
