version: "3.8"
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./src/data:/data
      - redis_data:/redis_data

  notebook:
    image: grosinosky/bigdata_fila3_jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "" # Désactive le token
      GRANT_SUDO: "yes"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url='/'"
    volumes:
      - ./src:/home/jovyan/work
    depends_on:
      - redis

  redis-setup:
    image: grosinosky/bigdata_fila3_jupyter
    volumes:
      - ./src:/home/jovyan/work
    depends_on:
      - redis
    command: bash -c "sleep 5 && /usr/local/bin/import_data.sh"

volumes:
  redis_data:
