version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
